[2024-11-04T01:43:40.470+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-04T01:43:40.492+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: slack-message-tutorial.send_message_to_slack manual__2024-11-04T01:43:38.448834+00:00 [queued]>
[2024-11-04T01:43:40.508+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: slack-message-tutorial.send_message_to_slack manual__2024-11-04T01:43:38.448834+00:00 [queued]>
[2024-11-04T01:43:40.508+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-04T01:43:40.538+0000] {taskinstance.py:2888} INFO - Executing <Task(SlackAPIPostOperator): send_message_to_slack> on 2024-11-04 01:43:38.448834+00:00
[2024-11-04T01:43:40.545+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=388) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T01:43:40.547+0000] {standard_task_runner.py:72} INFO - Started process 389 to run task
[2024-11-04T01:43:40.547+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'slack-message-tutorial', 'send_message_to_slack', 'manual__2024-11-04T01:43:38.448834+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/send_slack_message_tutorial.py', '--cfg-path', '/tmp/tmpn1ev6cdc']
[2024-11-04T01:43:40.548+0000] {standard_task_runner.py:105} INFO - Job 162: Subtask send_message_to_slack
[2024-11-04T01:43:40.595+0000] {task_command.py:467} INFO - Running <TaskInstance: slack-message-tutorial.send_message_to_slack manual__2024-11-04T01:43:38.448834+00:00 [running]> on host 5a41fc77ef88
[2024-11-04T01:43:40.677+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='slack-message-tutorial' AIRFLOW_CTX_TASK_ID='send_message_to_slack' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T01:43:38.448834+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T01:43:38.448834+00:00'
[2024-11-04T01:43:40.678+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-04T01:43:40.711+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/operators/slack.py", line 113, in execute
    self.hook.call(self.method, json=self.api_params)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack.py", line 186, in call
    return self.client.api_call(api_method, **kwargs)
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack.py", line 142, in client
    return WebClient(**self._get_conn_params())
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack.py", line 150, in _get_conn_params
    conn = self.get_connection(self.slack_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `slack_api_default` isn't defined
[2024-11-04T01:43:40.719+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=slack-message-tutorial, task_id=send_message_to_slack, run_id=manual__2024-11-04T01:43:38.448834+00:00, execution_date=20241104T014338, start_date=20241104T014340, end_date=20241104T014340
[2024-11-04T01:43:40.734+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-04T01:43:40.734+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 162 for task send_message_to_slack (The conn_id `slack_api_default` isn't defined; 389)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/operators/slack.py", line 113, in execute
    self.hook.call(self.method, json=self.api_params)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack.py", line 186, in call
    return self.client.api_call(api_method, **kwargs)
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack.py", line 142, in client
    return WebClient(**self._get_conn_params())
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack.py", line 150, in _get_conn_params
    conn = self.get_connection(self.slack_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `slack_api_default` isn't defined
[2024-11-04T01:43:40.762+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-04T01:43:40.778+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T01:43:40.781+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
